<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
use Kumwe\Integration\{RecordedDomainEvent,RecordedIntegrationEvent,RecordedEventEnvelope,EventSensitivity,EventSchemaDefinition,EventConsumerDefinition,EventContractRegistry,ProcessInstance,ProcessStatus,ProcessWorkItem,ProcessWorkKind,ProcessTransition,InboxClaimResult,InboxDisposition,OutboxLease,IntegrationContractValidator,PayloadSchemaValidator,WebhookContributionDefinition,ConsumerIdempotency};
$encoder=new ObservedEncoder();
$now=new DateTimeImmutable('2026-08-10T10:00:00Z');
$id='00000000-0000-7000-8000-000000000001';
$event=fn(array $payload=['record_id'=>'record-7'],?string $actor='actor-1',?string $system=null,EventSensitivity $sensitivity=EventSensitivity::INTERNAL)=>new RecordedDomainEvent($encoder,'business.record.changed',1,$id,$now,$actor,$system,'default','organization-1','business.record','record-7',3,'correlation-1','request-1',$sensitivity,$payload);
$domain=$event();$integration=RecordedIntegrationEvent::fromDomain($encoder,$domain);$restored=RecordedIntegrationEvent::fromArray($encoder,$integration->toArray());
check($domain->eventId()===$integration->eventId() && $integration->toArray()===$restored->toArray(),'Event conversion preserves identity and full envelope');
check($restored->actorId()==='actor-1' && $restored->systemIdentity()===null,'Human attribution survives roundtrip');
rejects(fn()=> $event(actor:'actor-1',system:'worker'));
rejects(fn()=> $event(actor:null,system:null));
rejects(fn()=> $event(['list']));
rejects(fn()=>RecordedIntegrationEvent::fromArray($encoder,$integration->toArray()+['extra'=>true]));
$bad=$integration->toArray();$bad['occurred_at']='2026-08-10 10:00:00 UTC';rejects(fn()=>RecordedIntegrationEvent::fromArray($encoder,$bad));
$bad=$integration->toArray();$bad['event_id']='INVALID';rejects(fn()=>RecordedIntegrationEvent::fromArray($encoder,$bad));
$deep=1;for($i=0;$i<17;$i++)$deep=['x'=>$deep];rejects(fn()=> $event($deep));
rejects(fn()=> $event(['x'=>array_fill(0,2049,1)]));
$encoder->bytes=65536;check($event()->payload()===['record_id'=>'record-7'],'Exact envelope byte ceiling accepted');
$encoder->bytes=65537;rejects(fn()=> $event());$encoder->bytes=null;
$schema=new EventSchemaDefinition($encoder,'business.record.changed',1,EventSensitivity::INTERNAL,['type'=>'object','required'=>['record_id'],'properties'=>['record_id'=>['type'=>'string']],'additionalProperties'=>false]);
$consumer=new EventConsumerDefinition('acme.search-index','business.record.changed',[1],'1.0.0');
$registry=new EventContractRegistry($encoder,[$schema],[$consumer]);$registry->assertEvent($event());
check($registry->consumer('acme.search-index')===$consumer && $registry->consumersFor($event())===[$consumer],'Registry resolves exact declared consumer');
rejects(fn()=> $registry->assertEvent($event(['unknown'=>true])));
rejects(fn()=> $registry->assertEvent($event(sensitivity:EventSensitivity::PUBLIC)));
rejects(fn()=> new EventContractRegistry($encoder,[$schema,$schema],[]));
rejects(fn()=> new EventContractRegistry($encoder,[],[$consumer]));
rejects(fn()=> $registry->replace([],[$consumer]));
check($registry->schema('business.record.changed',1)===$schema,'Rejected replacement leaves old registry intact');
$other=new EventConsumerDefinition('acme.future','business.record.changed',[2],'1.0.0');rejects(fn()=>new EventContractRegistry($encoder,[$schema],[$other]));
check(EventSchemaDefinition::fromArray($encoder,$schema->toArray())->toArray()===$schema->toArray(),'Schema roundtrip');
check(EventConsumerDefinition::fromArray($consumer->toArray())->toArray()===$consumer->toArray(),'Consumer roundtrip');
rejects(fn()=>EventConsumerDefinition::fromArray($consumer->toArray()+['extra'=>true]));
$before=$encoder->calls;
foreach([['x'=>1.5],['x'=>new stdClass()],['x'=>array_fill(0,513,1)]] as $bad)rejects(fn()=>IntegrationContractValidator::object($encoder,$bad,'Test'));
check($encoder->calls===$before,'Declaration prevalidation prevents generic encoder widening SDK profile');
$deep=1;for($i=0;$i<34;$i++)$deep=['x'=>$deep];rejects(fn()=>IntegrationContractValidator::object($encoder,$deep,'Test'));
$process=new ProcessInstance($encoder,$id,'purchase.fulfilment','order-77','default','organization-1','actor-1',null,1,ProcessStatus::RUNNING,['step'=>1],$now,$now);
$advanced=$process->transition(['step'=>2],ProcessStatus::RUNNING,$now->modify('+1 minute'));
$cancelled=$advanced->cancel('operator-7','Supplier declined.',$now->modify('+2 minutes'));
check($process->version()===1 && $advanced->version()===2 && $cancelled->version()===3,'Process transitions are immutable and increment version');
check($cancelled->status()===ProcessStatus::CANCELLED && $cancelled->state()===['step'=>2] && $cancelled->cancellationBy()==='operator-7','Cancellation retains state and operator attribution');
rejects(fn()=> $cancelled->transition(['step'=>3],ProcessStatus::RUNNING,$now->modify('+3 minutes')));
rejects(fn()=> $advanced->transition(['step'=>3],ProcessStatus::RUNNING,$now->modify('-1 second')));
$work=new ProcessWorkItem($encoder,$id,ProcessWorkKind::COMMAND,'inventory.reserve',['sku'=>'SKU-1'],$now);
$transition=new ProcessTransition($encoder,['step'=>2],ProcessStatus::RUNNING,[$work]);
check($transition->work()===[$work],'Process transition retains requested work');
rejects(fn()=> new ProcessTransition($encoder,['step'=>2],ProcessStatus::RUNNING,[$work,$work]));
rejects(fn()=> new InboxClaimResult(InboxDisposition::CLAIMED));
check((new InboxClaimResult(InboxDisposition::DUPLICATE))->lease===null,'Duplicate inbox result has no lease');
$validator=new PayloadSchemaValidator();
$validator->assertPayload(['type'=>'object','properties'=>['ids'=>['type'=>'array','items'=>['type'=>'integer'],'maxItems'=>2]],'additionalProperties'=>false],['ids'=>[1,2]]);check(true,'Typed bounded nested payload accepted');
rejects(fn()=> $validator->assertPayload(['type'=>'object','properties'=>['ids'=>['type'=>'array','items'=>['type'=>'integer'],'maxItems'=>2]]],['ids'=>[1,2,3]]));
$encoder->refuse=true;rejects(fn()=> $process->transition(['step'=>2],ProcessStatus::RUNNING,$now->modify('+1 minute')));$encoder->refuse=false;
fwrite(STDOUT,"integration: $assertions assertions passed\n");
